# Generated by Django 5.1.1 on 2024-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://private-user-images.githubusercontent.com/178132521/369594940-09a367c0-0869-411b-ba75-36b21d9e21b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4OTMxOTgsIm5iZiI6MTcyNjg5Mjg5OCwicGF0aCI6Ii8xNzgxMzI1MjEvMzY5NTk0OTQwLTA5YTM2N2MwLTA4NjktNDExYi1iYTc1LTM2YjIxZDllMjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwNDI4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDkwOGZmYzhmNGI3YmJkODc5NGUyODQ4NGIzMzQ1Y2FlZmZmMDdkMDkxYTMzYjMxOTc3YTNiNDk0ZjYzODIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wilXME2JwqD_7cWC2yduWb5R30rSydmK7G6pIiweuZY', max_length=255),
        ),
    ]
