# Generated by Django 5.1.1 on 2024-09-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default='https://private-user-images.githubusercontent.com/178132521/369594940-09a367c0-0869-411b-ba75-36b21d9e21b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODk2MDMsIm5iZiI6MTcyNzE4OTMwMywicGF0aCI6Ii8xNzgxMzI1MjEvMzY5NTk0OTQwLTA5YTM2N2MwLTA4NjktNDExYi1iYTc1LTM2YjIxZDllMjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNDQ4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTExMTdmYTVkMDEzZGY0M2E4NWUyM2EwZGFiOTBmODJiMzE1Y2M1NzdmZTQ4NjQ4ODJmZDk3YjFkNjdjMWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EAR_fR-_8DooRA-p0PTyiAzKRKQFQmTsxukcNmxVJg4'),
        ),
    ]
